### PR TITLE
Add new language

### PR DESCRIPTION
**Pull request by darkautism**
Added support for zh_tw and ja_jp.
The font file is based on the branch I forked.
This branch broke some functionality, so it currently only works on the esp32-s3-touch-lcd-1.46.
If the review finds it acceptable, I will commit the code for all boards.

### CODE REVIEW

**Comment by 78** [comment]
This is truly a nice work! Could you please submit the language part first while keeping the font part unchanged? Because any modification to the font part will cause compilation errors for zh-CN develeopers.

**Comment by darkautism** [comment]
Is there any plan to include additional fonts or implement CJK fonts to address the issue of missing characters?

**Comment by 78** [comment]
It's difficult to include all CJK characters into a pixel font without any
compression algorithm.
Currently 7k characters are used in Chinese fonts.
If we want to include all CJK fonts, we have to use 60k characters.
I have a plan to develop a function to download the font from the server in
the next major version.

kautism ***@***.***> 于2025年3月8日周六 16:31写道：

**Comment by hohosiu** [comment]
Looks like traditional Chinese is not working on most boards? How can I fix it? Thanks.

**Comment by darkautism** [comment]
> Looks like traditional Chinese is not working on most boards? How can I fix it? Thanks.

https://github.com/darkautism/xiaozhi-fonts

Using my fork fonts

**Comment by hohosiu** [comment]
it only work on esp32-s3-touch-lcd-1.46?

**Comment by darkautism** [comment]
you should change font name in your board.c
